name: "Safe Explorer"
help: 'Pytorch implementation of "Safe Exploration in Continuous Action Spaces".'
arguments:
  - name: "env"
    help: "Configuration related to simulation environments."
    properties:
      - name: "spaceship"
        help: "Spaceship environment configuration."
        properties:
          - name: "length"
            default: 2.5
          - name: "margin"
            default: 0.2
          - name: "agent_slack"
            default: 0.1
          - name: "frequency_ratio"
            default: 0.25
          - name: "target_noise_std"
            default: 0.05
          - name: "target_radius"
            default: 0.05
          - name: "corridor_episode_length"
            default: 15
          - name: "arena_episode_length"
            default: 45
          - name: "enable_reward_shaping"
            default: false
          - name: "is_arena"
            default: false
      - name: "ballnd"
        help: "Ball-ND environment configuration."
        properties:
          - name: "n"
            default: 1
          - name: "target_margin"
            default: 0.2
          - name: "agent_slack"
            default: 0.1
          - name: "episode_length"
            default: 15
          - name: "frequency_ratio"
            default: 0.025
          - name: "respawn_interval"
            default: 0.1
          - name: "target_noise_std"
            default: 0.05
          - name: "enable_reward_shaping"
            default: false
  - name: "ddpg"
    help: "Hyperparameters for DDPG algorithm."
    properties:
    - name: "actor"
      help: "Actor network parameters."
      properties:
        - name: "layers"
          default: [20, 20]
        - name: "init_bound"
          default: 0.003
    - name: "critic"
      help: "Critic network parameters."
      properties:
        - name: "layers"
          default: [50, 50]
        - name: "init_bound"
          default: 0.003
    - name: "trainer"
      help: "Training parameters."
      properties:
        - name: "seed"
          default: 0
        - name: "epochs"
          default: 100
        - name: "steps_per_epoch"
          default: 5000
        - name: "evaluation_steps"
          default: 500
        - name: "batch_size"
          default: 100
        - name: "max_episode_length"
          default: 100
        - name: "replay_buffer_size"
          default: 1000000
        - name: "discount_factor"
          default: 0.99
        - name: "polyak"
          default: 0.995
        - name: "actor_lr"
          default: 0.001
        - name: "critic_lr"
          default: 0.001
        - name: "start_steps"
          default: 10000
        - name: "action_noise_range"
          default: 0.01
        - name: "tensorboard_dir"
          default: "./runs/tensorboard/"
        - name: "use_gpu"
          default: false
  - name: "core"
    help: "Safe-Explorer core properties."
    properties:
      - name: "driver"
        help: "Driver configuration."
        properties:
          - name: "task"
            default: "ballnd"
